name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-68068ceb723e0e0001708013-66737fae6e73b202703a26f9b574e6346f   
      
      - name: Run API tests
        run: |
          postman collection run "postman/collections/santa.json" -e "santa-enviroment.postman_environment.json"
     
